[package]
name = "threads"
version = "0.1.0"
edition = "2018"


[dependencies]
oneshot = { git = "https://github.com/merl-twin/oneshot.git" }

crossbeam = "0.8"
lazy_static = "1.4"
log = "0.4"
time = "0.3"
